name: Build OpenCV

on:
  push:
    branches:
      - build-wasm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout Emscripten
        uses: actions/checkout@v2
        with:
          repository: emscripten-core/emsdk
          ref: 3.1.44
          path: emsdk
      - name: Checkout OpenCV
        uses: actions/checkout@v2
        with:
          repository: opencv/opencv
          ref: 4.8.0
          path: opencv
      - name: Setup Emscripten
        run: |-
          cd emsdk
          ./emsdk install 3.1.44
          ./emsdk activate 3.1.44
      - name: Patch OpenCV
        run: |-
          patch opencv/platforms/js/build_js.py build/opencv.patch
      - name: Build OpenCV
        run: |-
          source ./emsdk/emsdk_env.sh
          emcmake python ./opencv/platforms/js/build_js.py build_js --build_wasm --disable_single_file
          emcmake python ./opencv/platforms/js/build_js.py build_wasm --build_wasm
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./opencv/build
